# Generated by Django 2.0.6 on 2018-10-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Paragráfo único com no máximo 100 palavras.', verbose_name='Resumo (Breve descrição)')),
                ('goal', models.TextField(verbose_name='Objetivo')),
                ('public', models.CharField(max_length=200, verbose_name='Público Alvo')),
                ('vacancies', models.PositiveIntegerField(verbose_name='Número Máximo de Participantes')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Pré-requisitos')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Recursos necessários')),
                ('workload', models.PositiveIntegerField(verbose_name='Carga Horária')),
                ('status', models.IntegerField(default=1, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_events', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authors_events', to=settings.AUTH_USER_MODEL, verbose_name='Co-autores')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_events', to=settings.AUTH_USER_MODEL, verbose_name='Orientador')),
            ],
            options={
                'verbose_name_plural': 'Minicursos',
                'verbose_name': 'Minicurso',
            },
        ),
    ]
