# Generated by Django 2.1.2 on 2018-10-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_remove_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_authors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='event',
            name='author1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='author_events', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='co_authors_events', to=settings.AUTH_USER_MODEL, verbose_name='Co-autores'),
        ),
    ]
