# Generated by Django 2.1.2 on 2018-10-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20181023_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='author_events', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
